--------------------------------------------------------
--  File created - Tuesday-January-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence JENISSEPEDA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VIGNETTE"."JENISSEPEDA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table JENISSEPEDA
--------------------------------------------------------

  CREATE TABLE "VIGNETTE"."JENISSEPEDA" 
   (	"JENISID" NUMBER(*,0), 
	"NAMAJENIS" VARCHAR2(20 BYTE), 
	"DESKRIPSI" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEPEDA
--------------------------------------------------------

  CREATE TABLE "VIGNETTE"."SEPEDA" 
   (	"SEPEDAID" VARCHAR2(20 BYTE), 
	"JENISID" NUMBER(*,0), 
	"NAMASEPEDA" VARCHAR2(30 BYTE), 
	"ISACTIVE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "VIGNETTE"."TB_USER" 
   (	"USERID" VARCHAR2(200 BYTE), 
	"NAMA" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ISACTIVE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "VIGNETTE"."TRANSACTION" 
   (	"TRANSACTIONID" VARCHAR2(30 BYTE), 
	"USERID" VARCHAR2(200 BYTE), 
	"SEPEDAID" VARCHAR2(20 BYTE), 
	"STARTEDDATE" TIMESTAMP (6), 
	"ENDDATE" TIMESTAMP (6), 
	"STATUS" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into VIGNETTE.JENISSEPEDA
SET DEFINE OFF;
REM INSERTING into VIGNETTE.SEPEDA
SET DEFINE OFF;
REM INSERTING into VIGNETTE.TB_USER
SET DEFINE OFF;
REM INSERTING into VIGNETTE.TRANSACTION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TRANSAKSI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIGNETTE"."TRANSAKSI_PK" ON "VIGNETTE"."TRANSACTION" ("TRANSACTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SEPEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIGNETTE"."SEPEDA_PK" ON "VIGNETTE"."SEPEDA" ("SEPEDAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIGNETTE"."CUSTOMER_PK" ON "VIGNETTE"."TB_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JENISSEPEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIGNETTE"."JENISSEPEDA_PK" ON "VIGNETTE"."JENISSEPEDA" ("JENISID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger JENISSEPEDA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VIGNETTE"."JENISSEPEDA_TRG" 
BEFORE INSERT ON JENISSEPEDA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.JENISID IS NULL THEN
      SELECT JENISSEPEDA_SEQ.NEXTVAL INTO :NEW.JENISID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VIGNETTE"."JENISSEPEDA_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table SEPEDA
--------------------------------------------------------

  ALTER TABLE "VIGNETTE"."SEPEDA" ADD CONSTRAINT "SEPEDA_PK" PRIMARY KEY ("SEPEDAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VIGNETTE"."SEPEDA" MODIFY ("ISACTIVE" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."SEPEDA" MODIFY ("NAMASEPEDA" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."SEPEDA" MODIFY ("JENISID" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."SEPEDA" MODIFY ("SEPEDAID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "VIGNETTE"."TRANSACTION" ADD CONSTRAINT "TRANSAKSI_PK" PRIMARY KEY ("TRANSACTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VIGNETTE"."TRANSACTION" MODIFY ("STARTEDDATE" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TRANSACTION" MODIFY ("SEPEDAID" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TRANSACTION" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TRANSACTION" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "VIGNETTE"."TB_USER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VIGNETTE"."TB_USER" MODIFY ("ISACTIVE" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TB_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TB_USER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TB_USER" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."TB_USER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JENISSEPEDA
--------------------------------------------------------

  ALTER TABLE "VIGNETTE"."JENISSEPEDA" ADD CONSTRAINT "JENISSEPEDA_PK" PRIMARY KEY ("JENISID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "VIGNETTE"."JENISSEPEDA" MODIFY ("NAMAJENIS" NOT NULL ENABLE);
  ALTER TABLE "VIGNETTE"."JENISSEPEDA" MODIFY ("JENISID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "VIGNETTE"."TRANSACTION" ADD CONSTRAINT "FK_SEPEDAID" FOREIGN KEY ("SEPEDAID")
	  REFERENCES "VIGNETTE"."SEPEDA" ("SEPEDAID") ENABLE;
  ALTER TABLE "VIGNETTE"."TRANSACTION" ADD CONSTRAINT "FK_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "VIGNETTE"."TB_USER" ("USERID") ENABLE;
